"""baseline schema

Revision ID: f664dda8ffca
Revises:
Create Date: 2026-06-29 21:50:14.169192
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f664dda8ffca"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "api_keys",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("key_prefix", sa.String(length=16), nullable=False),
        sa.Column("max_cost_usd", sa.Float(), nullable=False),
        sa.Column("max_cost_monthly", sa.Float(), nullable=False),
        sa.Column("max_requests_per_min", sa.Integer(), nullable=False),
        sa.Column("total_requests", sa.Integer(), nullable=False),
        sa.Column("total_cost", sa.Float(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("allowed_models", sa.Text(), nullable=True),
        sa.Column("denied_models", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_api_keys_key_hash"), "api_keys", ["key_hash"], unique=True)
    op.create_table(
        "approval_requests",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("run_id", sa.String(length=50), nullable=False),
        sa.Column("agent_name", sa.String(length=200), nullable=False),
        sa.Column("scope", sa.String(length=20), nullable=False),
        sa.Column("approval_type", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("current_value", sa.Float(), nullable=False),
        sa.Column("limit_value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(length=20), nullable=False),
        sa.Column("timeout_sec", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=80), nullable=True),
        sa.Column("api_key_id", sa.String(length=50), nullable=True),
        sa.Column("channels_json", sa.JSON(), nullable=False),
        sa.Column("alert_email", sa.String(length=320), nullable=True),
        sa.Column("alert_webhook_url", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("resolution_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.Column("resolved_by", sa.String(length=120), nullable=True),
        sa.Column("resolution_note", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_approval_requests_api_key_id"), "approval_requests", ["api_key_id"], unique=False
    )
    op.create_index(
        op.f("ix_approval_requests_run_id"), "approval_requests", ["run_id"], unique=False
    )
    op.create_index(
        op.f("ix_approval_requests_session_id"), "approval_requests", ["session_id"], unique=False
    )
    op.create_table(
        "policies",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("allowed_actions", sa.JSON(), nullable=True),
        sa.Column("denied_actions", sa.JSON(), nullable=True),
        sa.Column("rate_limits", sa.JSON(), nullable=True),
        sa.Column("require_approval", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_policies_id"), "policies", ["id"], unique=False)
    op.create_table(
        "runs",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("agent_name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("total_cost", sa.Float(), nullable=False),
        sa.Column("total_steps", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("max_cost_usd", sa.Float(), nullable=False),
        sa.Column("max_steps_limit", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("error_details", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_runs_id"), "runs", ["id"], unique=False)
    op.create_table(
        "api_key_enforcements",
        sa.Column("api_key_id", sa.String(length=50), nullable=False),
        sa.Column("enforcement_mode", sa.String(length=20), nullable=False),
        sa.Column("alert_threshold", sa.Float(), nullable=False),
        sa.Column("alert_timeout_sec", sa.Integer(), nullable=False),
        sa.Column("alert_channels_json", sa.JSON(), nullable=False),
        sa.Column("alert_email", sa.String(length=320), nullable=True),
        sa.Column("alert_webhook_url", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["api_key_id"],
            ["api_keys.id"],
        ),
        sa.PrimaryKeyConstraint("api_key_id"),
    )
    op.create_table(
        "steps",
        sa.Column("id", sa.String(length=50), nullable=False),
        sa.Column("run_id", sa.String(length=50), nullable=False),
        sa.Column("step_number", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=200), nullable=False),
        sa.Column("tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_steps_run_id"), "steps", ["run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_steps_run_id"), table_name="steps")
    op.drop_table("steps")
    op.drop_table("api_key_enforcements")
    op.drop_index(op.f("ix_runs_id"), table_name="runs")
    op.drop_table("runs")
    op.drop_index(op.f("ix_policies_id"), table_name="policies")
    op.drop_table("policies")
    op.drop_index(op.f("ix_approval_requests_session_id"), table_name="approval_requests")
    op.drop_index(op.f("ix_approval_requests_run_id"), table_name="approval_requests")
    op.drop_index(op.f("ix_approval_requests_api_key_id"), table_name="approval_requests")
    op.drop_table("approval_requests")
    op.drop_index(op.f("ix_api_keys_key_hash"), table_name="api_keys")
    op.drop_table("api_keys")
    # ### end Alembic commands ###
