"""add runs.api_key_id

Revision ID: d22fd4232656
Revises: f664dda8ffca
Create Date: 2026-06-30 10:56:37.308178
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d22fd4232656"
down_revision: Union[str, None] = "f664dda8ffca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Nullable column: existing rows backfill to NULL, which the data-plane
    # treats as "owned by nobody" and keeps visible to everyone.
    op.add_column("runs", sa.Column("api_key_id", sa.String(length=50), nullable=True))
    op.create_index(op.f("ix_runs_api_key_id"), "runs", ["api_key_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_runs_api_key_id"), table_name="runs")
    op.drop_column("runs", "api_key_id")
    # ### end Alembic commands ###
